/** IProduct - product actions enum */
export enum EPActionsTypes {
    FETCH_PRODUCTS_INIT = "FETCH_PRODUCTS_INIT",
    FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR",
    FETCH_PRODUCTS_SEARCH = "FETCH_PRODUCTS_SEARCH",
    FETCH_PRODUCTS_SEARCH_ERROR = "FETCH_PRODUCTS_SEARCH_ERROR",
}
